services:
  algorithmicdev-backend:
    image: vivek6201/algorithmicdev_backend:latest
    container_name: algorithmicdev-backend
    restart: unless-stopped
    user: "1000:1000"
    command: [ "uv", "run", "start" ]
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - UV_CACHE_DIR=/app/.cache/uv
      - UV_NO_CACHE=1
    networks:
      - app-network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  app-network:
    driver: bridge
