"""updated metadata table

Revision ID: 04c33fc6931a
Revises: ca21c393449a
Create Date: 2026-01-07 08:01:43.521925

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '04c33fc6931a'
down_revision: Union[str, Sequence[str], None] = 'ca21c393449a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nodecontent',
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('node_id', sa.Integer(), nullable=False),
    sa.Column('editorial', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('video_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['node_id'], ['node.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nodecontent_deleted_at'), 'nodecontent', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_nodecontent_node_id'), 'nodecontent', ['node_id'], unique=True)
    op.drop_index(op.f('ix_nodemetadata_deleted_at'), table_name='nodemetadata')
    op.drop_index(op.f('ix_nodemetadata_node_id'), table_name='nodemetadata')
    op.drop_table('nodemetadata')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nodemetadata',
    sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('node_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('content', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['node_id'], ['node.id'], name=op.f('nodemetadata_node_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('nodemetadata_pkey'))
    )
    op.create_index(op.f('ix_nodemetadata_node_id'), 'nodemetadata', ['node_id'], unique=True)
    op.create_index(op.f('ix_nodemetadata_deleted_at'), 'nodemetadata', ['deleted_at'], unique=False)
    op.drop_index(op.f('ix_nodecontent_node_id'), table_name='nodecontent')
    op.drop_index(op.f('ix_nodecontent_deleted_at'), table_name='nodecontent')
    op.drop_table('nodecontent')
    # ### end Alembic commands ###
