"""made field mandatory

Revision ID: 0ad8678ebfde
Revises: bc9885302b7d
Create Date: 2025-12-09 15:42:51.748802

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0ad8678ebfde'
down_revision: Union[str, Sequence[str], None] = 'bc9885302b7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('job', 'job_type',
               existing_type=postgresql.ENUM('FULL_TIME', 'PART_TIME', 'CONTRACT', 'INTERN', name='jobtype'),
               nullable=False)
    op.alter_column('job', 'job_mode',
               existing_type=postgresql.ENUM('REMOTE', 'ON_SITE', 'HYBRID', name='jobmode'),
               nullable=False)
    op.alter_column('job', 'listing_type',
               existing_type=postgresql.ENUM('ThirdParty', 'Direct', name='listingtype'),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('job', 'listing_type',
               existing_type=postgresql.ENUM('ThirdParty', 'Direct', name='listingtype'),
               nullable=True)
    op.alter_column('job', 'job_mode',
               existing_type=postgresql.ENUM('REMOTE', 'ON_SITE', 'HYBRID', name='jobmode'),
               nullable=True)
    op.alter_column('job', 'job_type',
               existing_type=postgresql.ENUM('FULL_TIME', 'PART_TIME', 'CONTRACT', 'INTERN', name='jobtype'),
               nullable=True)
    # ### end Alembic commands ###
