"""change_session_id_to_uuid

Revision ID: 15fb43cffae1
Revises: 4a11838802ec
Create Date: 2026-02-05 19:03:57.905274

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '15fb43cffae1'
down_revision: Union[str, Sequence[str], None] = '4a11838802ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Truncate tables to allow clean type change
    op.execute("TRUNCATE TABLE session CASCADE")
    op.execute("TRUNCATE TABLE admin_sessions CASCADE")

    # Drop default value (sequence) which causes type mismatch
    op.execute("ALTER TABLE session ALTER COLUMN id DROP DEFAULT")
    op.execute("ALTER TABLE admin_sessions ALTER COLUMN id DROP DEFAULT")

    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('admin_sessions', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.Uuid(),
               existing_nullable=False,
               postgresql_using='id::text::uuid')
    op.alter_column('session', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.Uuid(),
               existing_nullable=False,
               postgresql_using='id::text::uuid')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("TRUNCATE TABLE session CASCADE")
    op.execute("TRUNCATE TABLE admin_sessions CASCADE")
    
    # We can't easily restore the sequence default without knowing the sequence name or recreating it, 
    # but strictly for downgrade we can just change type back to INT.
    # Ideally we should re-attach a sequence, but for dev revert this is usually acceptable or we just assume we won't downgrade.
    
    op.alter_column('session', 'id',
               existing_type=sa.Uuid(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               postgresql_using='id::text::int') 
    op.alter_column('admin_sessions', 'id',
               existing_type=sa.Uuid(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               postgresql_using='id::text::int')
    
    # Create sequences again if needed... simplistic approach:
    # op.execute("CREATE SEQUENCE session_id_seq OWNED BY session.id")
    # op.execute("ALTER TABLE session ALTER COLUMN id SET DEFAULT nextval('session_id_seq')")
    # Same for admin_sessions
    # ### end Alembic commands ###
