"""added education categories

Revision ID: 18876e730352
Revises: 78b02ae21445
Create Date: 2025-12-13 16:39:08.667416

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '18876e730352'
down_revision: Union[str, Sequence[str], None] = '78b02ae21445'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('educationcategory',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_educationcategory_id'), 'educationcategory', ['id'], unique=False)
    op.create_table('blogcategorylink',
    sa.Column('blog_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['blog_id'], ['blog.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['educationcategory.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('blog_id', 'category_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('blogcategorylink')
    op.drop_index(op.f('ix_educationcategory_id'), table_name='educationcategory')
    op.drop_table('educationcategory')
    # ### end Alembic commands ###
