"""added tutorial models

Revision ID: 20e30c62f58a
Revises: 3161791b71a4
Create Date: 2025-12-28 09:52:24.560220

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '20e30c62f58a'
down_revision: Union[str, Sequence[str], None] = '3161791b71a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nodetype',
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('icon', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_leaf', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nodetype_deleted_at'), 'nodetype', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_nodetype_name'), 'nodetype', ['name'], unique=True)
    op.create_table('tutorial',
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tutorial_deleted_at'), 'tutorial', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_tutorial_slug'), 'tutorial', ['slug'], unique=True)
    op.create_table('node',
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('tutorial_id', sa.Integer(), nullable=False),
    sa.Column('node_type_id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['node_type_id'], ['nodetype.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['node.id'], ),
    sa.ForeignKeyConstraint(['tutorial_id'], ['tutorial.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_node_deleted_at'), 'node', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_node_node_type_id'), 'node', ['node_type_id'], unique=False)
    op.create_index(op.f('ix_node_tutorial_id'), 'node', ['tutorial_id'], unique=False)
    op.create_table('tutorialcategorylink',
    sa.Column('tutorial_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['educationcategory.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tutorial_id'], ['tutorial.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tutorial_id', 'category_id')
    )
    op.create_table('nodemetadata',
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('node_id', sa.Integer(), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['node_id'], ['node.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nodemetadata_deleted_at'), 'nodemetadata', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_nodemetadata_node_id'), 'nodemetadata', ['node_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_nodemetadata_node_id'), table_name='nodemetadata')
    op.drop_index(op.f('ix_nodemetadata_deleted_at'), table_name='nodemetadata')
    op.drop_table('nodemetadata')
    op.drop_table('tutorialcategorylink')
    op.drop_index(op.f('ix_node_tutorial_id'), table_name='node')
    op.drop_index(op.f('ix_node_node_type_id'), table_name='node')
    op.drop_index(op.f('ix_node_deleted_at'), table_name='node')
    op.drop_table('node')
    op.drop_index(op.f('ix_tutorial_slug'), table_name='tutorial')
    op.drop_index(op.f('ix_tutorial_deleted_at'), table_name='tutorial')
    op.drop_table('tutorial')
    op.drop_index(op.f('ix_nodetype_name'), table_name='nodetype')
    op.drop_index(op.f('ix_nodetype_deleted_at'), table_name='nodetype')
    op.drop_table('nodetype')
    # ### end Alembic commands ###
