"""add user_reaction table

Revision ID: 2b938f7bd5b0
Revises: 52456584842f
Create Date: 2025-12-22 00:21:34.746600

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '2b938f7bd5b0'
down_revision: Union[str, Sequence[str], None] = '52456584842f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('userreaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('content_type', sa.Enum('BLOG', 'TUTORIAL', name='contenttype'), nullable=False),
    sa.Column('content_id', sa.Integer(), nullable=False),
    sa.Column('reaction', sa.Enum('LIKE', 'DISLIKE', name='reactiontype'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'content_type', 'content_id', name='uq_user_content_reaction')
    )
    op.create_index('idx_content_reactions', 'userreaction', ['content_type', 'content_id'], unique=False)
    op.create_index(op.f('ix_userreaction_content_id'), 'userreaction', ['content_id'], unique=False)
    op.create_index(op.f('ix_userreaction_user_id'), 'userreaction', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_userreaction_user_id'), table_name='userreaction')
    op.drop_index(op.f('ix_userreaction_content_id'), table_name='userreaction')
    op.drop_index('idx_content_reactions', table_name='userreaction')
    op.drop_table('userreaction')
    # ### end Alembic commands ###
