"""added exp in job

Revision ID: 3161791b71a4
Revises: 98735559d2c4
Create Date: 2025-12-27 16:58:50.787975

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '3161791b71a4'
down_revision: Union[str, Sequence[str], None] = '98735559d2c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job', sa.Column('min_experience', sa.Integer(), nullable=True))
    op.add_column('job', sa.Column('max_experience', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job', 'max_experience')
    op.drop_column('job', 'min_experience')
    # ### end Alembic commands ###
