"""updated user roles

Revision ID: 48e403794ba5
Revises: 083f2e32936f
Create Date: 2025-11-28 14:58:21.943178

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '48e403794ba5'
down_revision: Union[str, Sequence[str], None] = '083f2e32936f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE role RENAME TO role_old")
    op.execute("CREATE TYPE role AS ENUM('CANDIDATE', 'RECRUITER')")
    op.execute("ALTER TABLE users ALTER COLUMN role TYPE role USING role::text::role")
    op.execute("DROP TYPE role_old")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
