"""add admin to job

Revision ID: 5f46d8c501cd
Revises: 8b0374255e8e
Create Date: 2025-11-28 10:35:23.017398

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '5f46d8c501cd'
down_revision: Union[str, Sequence[str], None] = '8b0374255e8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job', sa.Column('admin_id', sa.Integer(), nullable=True))
    op.alter_column('job', 'owner_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'job', 'admin', ['admin_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'job', type_='foreignkey')
    op.alter_column('job', 'owner_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('job', 'admin_id')
    # ### end Alembic commands ###
