"""fix

Revision ID: 6693e85d5e8e
Revises: bba2eb905ba0
Create Date: 2025-11-23 17:52:28.712509

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6693e85d5e8e'
down_revision: Union[str, Sequence[str], None] = 'bba2eb905ba0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('job', 'job_type',
               existing_type=postgresql.ENUM('FULL_TIME', 'PART_TIME', 'CONTRACT', 'INTERN', name='jobtype'),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('job', 'job_type',
               existing_type=postgresql.ENUM('FULL_TIME', 'PART_TIME', 'CONTRACT', 'INTERN', name='jobtype'),
               nullable=False)
    # ### end Alembic commands ###
