"""update user_reaction to use content_slug

Revision ID: 8f6400ddec1e
Revises: 2b938f7bd5b0
Create Date: 2025-12-22 01:25:30.351448

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8f6400ddec1e'
down_revision: Union[str, Sequence[str], None] = '2b938f7bd5b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('userreaction', sa.Column('content_slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.drop_index(op.f('idx_content_reactions'), table_name='userreaction')
    op.drop_index(op.f('ix_userreaction_content_id'), table_name='userreaction')
    op.drop_constraint(op.f('uq_user_content_reaction'), 'userreaction', type_='unique')
    op.create_unique_constraint('uq_user_content_reaction', 'userreaction', ['user_id', 'content_slug'])
    op.create_index('idx_user_content_reaction', 'userreaction', ['user_id', 'content_slug'], unique=False)
    op.create_index(op.f('ix_userreaction_content_slug'), 'userreaction', ['content_slug'], unique=False)
    op.drop_column('userreaction', 'content_id')
    op.drop_column('userreaction', 'content_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('userreaction', sa.Column('content_type', postgresql.ENUM('BLOG', 'TUTORIAL', name='contenttype'), autoincrement=False, nullable=False))
    op.add_column('userreaction', sa.Column('content_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_userreaction_content_slug'), table_name='userreaction')
    op.drop_index('idx_user_content_reaction', table_name='userreaction')
    op.drop_constraint('uq_user_content_reaction', 'userreaction', type_='unique')
    op.create_unique_constraint(op.f('uq_user_content_reaction'), 'userreaction', ['user_id', 'content_type', 'content_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_userreaction_content_id'), 'userreaction', ['content_id'], unique=False)
    op.create_index(op.f('idx_content_reactions'), 'userreaction', ['content_type', 'content_id'], unique=False)
    op.drop_column('userreaction', 'content_slug')
    # ### end Alembic commands ###
