"""added uniue constraints on slug

Revision ID: 93655ab7fd95
Revises: e14c74f6d047
Create Date: 2025-12-28 11:13:44.401524

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '93655ab7fd95'
down_revision: Union[str, Sequence[str], None] = 'e14c74f6d047'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_node_slug'), 'node', ['slug'], unique=False)
    op.create_index('uq_node_parent_slug', 'node', ['parent_id', 'slug'], unique=True, postgresql_where='parent_id IS NOT NULL')
    op.create_index('uq_node_tutorial_slug_root', 'node', ['tutorial_id', 'slug'], unique=True, postgresql_where='parent_id IS NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_node_tutorial_slug_root', table_name='node', postgresql_where='parent_id IS NULL')
    op.drop_index('uq_node_parent_slug', table_name='node', postgresql_where='parent_id IS NOT NULL')
    op.drop_index(op.f('ix_node_slug'), table_name='node')
    # ### end Alembic commands ###
