"""add_cascade_delete_to_category_foreign_key

Revision ID: 958443ac3f1b
Revises: 063672833f97
Create Date: 2025-11-27 19:55:16.812955

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '958443ac3f1b'
down_revision: Union[str, Sequence[str], None] = '063672833f97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('jobcategorylink_category_id_fkey'), 'jobcategorylink', type_='foreignkey')
    op.create_foreign_key(None, 'jobcategorylink', 'category', ['category_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'jobcategorylink', type_='foreignkey')
    op.create_foreign_key(op.f('jobcategorylink_category_id_fkey'), 'jobcategorylink', 'category', ['category_id'], ['id'])
    # ### end Alembic commands ###
