"""updated job status

Revision ID: 98735559d2c4
Revises: d0e7c1fbb4d3
Create Date: 2025-12-25 21:15:07.581192

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '98735559d2c4'
down_revision: Union[str, Sequence[str], None] = 'd0e7c1fbb4d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("UPDATE job SET status = 'DRAFT' WHERE status IS NULL")
    op.alter_column('job', 'status',
               existing_type=postgresql.ENUM('DRAFT', 'PUBLISHED', name='jobstatus'),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('job', 'status',
               existing_type=postgresql.ENUM('DRAFT', 'PUBLISHED', name='jobstatus'),
               nullable=True)
    # ### end Alembic commands ###
