"""add max_sessions to users

Revision ID: 9fb0be0f31f6
Revises: 15fb43cffae1
Create Date: 2026-02-05 19:39:32.832606

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '9fb0be0f31f6'
down_revision: Union[str, Sequence[str], None] = '15fb43cffae1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('max_sessions', sa.Integer(), server_default='2', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'max_sessions')
    # ### end Alembic commands ###
