"""added blog status

Revision ID: b6399eb0d3ab
Revises: 18876e730352
Create Date: 2025-12-13 21:45:48.378056

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b6399eb0d3ab'
down_revision: Union[str, Sequence[str], None] = '18876e730352'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Create the blogstatus enum type explicitly
    blog_status = sa.Enum('DRAFT', 'PUBLISHED', name='blogstatus')
    blog_status.create(op.get_bind())

    op.add_column('blog', sa.Column('status', blog_status, nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blog', 'status')

    # Drop the blogstatus enum type explicitly
    blog_status = sa.Enum('DRAFT', 'PUBLISHED', name='blogstatus')
    blog_status.drop(op.get_bind())
    # ### end Alembic commands ###
