"""add job model column

Revision ID: bc9885302b7d
Revises: 48e403794ba5
Create Date: 2025-12-09 15:35:00.629452

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'bc9885302b7d'
down_revision: Union[str, Sequence[str], None] = '48e403794ba5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    job_mode_enum = sa.Enum('REMOTE', 'ON_SITE', 'HYBRID', name='jobmode')
    job_mode_enum.create(op.get_bind())
    op.add_column('job', sa.Column('job_mode', job_mode_enum, nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job', 'job_mode')
    job_mode_enum = sa.Enum('REMOTE', 'ON_SITE', 'HYBRID', name='jobmode')
    job_mode_enum.drop(op.get_bind())
    # ### end Alembic commands ###
