"""changed node tutorial relationship

Revision ID: ca21c393449a
Revises: 437512bf4bc1
Create Date: 2025-12-29 11:46:14.352248

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ca21c393449a'
down_revision: Union[str, Sequence[str], None] = '437512bf4bc1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('node', sa.Column('tutorial_slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.drop_index(op.f('ix_node_tutorial_id'), table_name='node')
    op.drop_index(op.f('uq_node_tutorial_slug_root'), table_name='node', postgresql_where='(parent_id IS NULL)')
    op.create_index('uq_node_tutorial_slug_root', 'node', ['tutorial_slug', 'slug'], unique=True, postgresql_where='parent_id IS NULL AND deleted_at IS NULL')
    op.create_index(op.f('ix_node_tutorial_slug'), 'node', ['tutorial_slug'], unique=False)
    op.drop_constraint(op.f('node_tutorial_id_fkey'), 'node', type_='foreignkey')
    op.create_foreign_key(None, 'node', 'tutorial', ['tutorial_slug'], ['slug'])
    op.drop_column('node', 'tutorial_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('node', sa.Column('tutorial_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'node', type_='foreignkey')
    op.create_foreign_key(op.f('node_tutorial_id_fkey'), 'node', 'tutorial', ['tutorial_id'], ['id'])
    op.drop_index(op.f('ix_node_tutorial_slug'), table_name='node')
    op.drop_index('uq_node_tutorial_slug_root', table_name='node', postgresql_where='parent_id IS NULL AND deleted_at IS NULL')
    op.create_index(op.f('uq_node_tutorial_slug_root'), 'node', ['tutorial_id', 'slug'], unique=True, postgresql_where='(parent_id IS NULL)')
    op.create_index(op.f('ix_node_tutorial_id'), 'node', ['tutorial_id'], unique=False)
    op.drop_column('node', 'tutorial_slug')
    # ### end Alembic commands ###
