"""drop blogmetadata table

Revision ID: d0e7c1fbb4d3
Revises: 8f6400ddec1e
Create Date: 2025-12-22 01:45:34.396240

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd0e7c1fbb4d3'
down_revision: Union[str, Sequence[str], None] = '8f6400ddec1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_blogmetadata_id'), table_name='blogmetadata')
    op.drop_table('blogmetadata')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blogmetadata',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('blog_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('likes', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('dislikes', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['blog_id'], ['blog.id'], name=op.f('blogmetadata_blog_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('blogmetadata_pkey'))
    )
    op.create_index(op.f('ix_blogmetadata_id'), 'blogmetadata', ['id'], unique=False)
    # ### end Alembic commands ###
