"""Add email verification fields and improve session security

Revision ID: de34f3499dd3
Revises: 4294286305ed
Create Date: 2025-11-24 08:34:09.017475

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'de34f3499dd3'
down_revision: Union[str, Sequence[str], None] = '4294286305ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add email_verified as nullable first to avoid constraint violation
    op.add_column('users', sa.Column('email_verified', sa.Boolean(), nullable=True))
    
    # Set default value for existing users (mark them as verified to allow login)
    op.execute("UPDATE users SET email_verified = TRUE WHERE email_verified IS NULL")
    
    # Now make the column NOT NULL
    op.alter_column('users', 'email_verified', nullable=False)
    
    # Add other columns
    op.add_column('users', sa.Column('verification_token', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('users', sa.Column('verification_token_expires', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'verification_token_expires')
    op.drop_column('users', 'verification_token')
    op.drop_column('users', 'email_verified')
    # ### end Alembic commands ###
