"""updated tutorials models

Revision ID: e14c74f6d047
Revises: 20e30c62f58a
Create Date: 2025-12-28 10:55:28.690132

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e14c74f6d047'
down_revision: Union[str, Sequence[str], None] = '20e30c62f58a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_node_is_published'), 'node', ['is_published'], unique=False)
    op.create_index(op.f('ix_nodetype_is_leaf'), 'nodetype', ['is_leaf'], unique=False)
    op.create_index(op.f('ix_tutorial_is_published'), 'tutorial', ['is_published'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tutorial_is_published'), table_name='tutorial')
    op.drop_index(op.f('ix_nodetype_is_leaf'), table_name='nodetype')
    op.drop_index(op.f('ix_node_is_published'), table_name='node')
    # ### end Alembic commands ###
